variable "backend-1_instance_type" {}
variable "backend-1_key_name" {}
variable "backend-1_ami" {}
variable "frontend-1_instance_type" {}
variable "frontend-1_key_name" {}
variable "frontend-1_ami" {}
variable "region_number" {}
variable "az_number1" {}
variable "database-1_key_name" {}
variable "database-1_instance_type" {}
variable "database-1_ami" {}
variable "backend-2_instance_type" {}
variable "backend-2_key_name" {}
variable "backend-2_ami" {}
variable "frontend-2_instance_type" {}
variable "frontend-2_key_name" {}
variable "frontend-2_ami" {}
variable "database-2_key_name" {}
variable "database-2_instance_type" {}
variable "database-2_ami" {}

